on: [push]

name: Cross CI

jobs:
  cross:
    name: Rust ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install --assume-yes git clang curl libssl-dev llvm libudev-dev make protobuf-compiler
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: stable
          target: ${{matrix.target}}, wasm32-unknown-unknown
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: nightly
          target: ${{matrix.target}}, wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{matrix.target}} --release +nightly
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}-binary
          path: target/${{matrix.target}}/release/node-template
